apiVersion: v1
kind: Pod
metadata:
  name: pod-https
  labels:
    app: https
spec:
  containers:
    - name: container
      image: wngud1/hoeng:main-6552a9218968342aac6956ddc1cc71e8ea8f4f52
      env:
        - name: TZ
          value: Asia/Seoul

        # ===========================
        # MySQL
        # ===========================
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-external.default.svc.cluster.local:3306/board?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: workly-mysql-secret
              key: MYSQL_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: workly-mysql-secret
              key: MYSQL_PASSWORD
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: com.mysql.cj.jdbc.Driver

        # ===========================
        # AWS / S3
        # ===========================
        - name: SPRING_APPLICATION_JSON
          valueFrom:
            secretKeyRef:
              name: workly-s3-secret
              key: SPRING_APPLICATION_JSON

        # ===========================
        # Redis
        # ===========================
        - name: SPRING_DATA_REDIS_HOST
          value: redis-service.default.svc.cluster.local
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"

        - name: SPRING_ELASTICSEARCH_URIS
          valueFrom:
              secretKeyRef:
                name: workly-es
                key: host

        - name: SPRING_ELASTICSEARCH_USERNAME
          valueFrom:
                  secretKeyRef:
                    name: workly-es
                    key: username

        - name: SPRING_ELASTICSEARCH_PASSWORD
          valueFrom:
                  secretKeyRef:
                    name: workly-es
                    key: password

        - name: ELASTICSEARCH_API_KEY
          valueFrom:
                  secretKeyRef:
                    name: workly-es
                    key: apikey
        # ===========================
        # RabbitMQ
        # ===========================
        - name: SPRING_RABBITMQ_HOST
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: SPRING_RABBITMQ_HOST
        - name: SPRING_RABBITMQ_PORT
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: SPRING_RABBITMQ_PORT
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: SPRING_RABBITMQ_USERNAME
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: SPRING_RABBITMQ_PASSWORD

        # ===========================
        # JWT Secret
        # ===========================
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: workly-jwt-secret
              key: JWT_SECRET

      envFrom:
        - secretRef:
            name: workly-config


  terminationGracePeriodSeconds: 0
