apiVersion: v1
kind: Pod
metadata:
  name: pod-https
  labels:
    app: https
spec:
  containers:
    - name: container
      image: wngud1/hoeng:6.0.4
      env:
        - name: TZ
          value: "Asia/Seoul"
  terminationGracePeriodSeconds: 0
---
