apiVersion: v1
kind: Pod
metadata:
  name: pod-https
  labels:
    app: https
spec:
  containers:
    - name: container
      image: wngud1/hoeng:main-6552a9218968342aac6956ddc1cc71e8ea8f4f52
      env:
        - name: TZ
          value: Asia/Seoul
        - name: SPRING_DATA_MYSQL_URI
          valueFrom:
            secretKeyRef:
              name: workly-mysql-secret
              key: SPRING_DATA_MYSQL_URI
        - name: SPRING_APPLICATION_JSON
          valueFrom:
            secretKeyRef:
              name: workly-s3-secret
              key: SPRING_APPLICATION_JSON
        - name: SPRING_DATA_REDIS_HOST
          value: redis-service.default.svc.cluster.local
        - name: SPRING_DATA_REDIS_PORT
          value: '6379'
      envFrom:
          - secretRef:
              name: workly-config
          - secretRef:
              name: workly-es
  terminationGracePeriodSeconds: 0
