apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-frontend
spec:
  selector:
    matchLabels:
      app: vue
  template:
    metadata:
      labels:
        app: vue
    spec:
      containers:
        - name: vue
          image: wngud1/vue-frontend:main-86ab940452fa2ef14d5c6ebcac98ffde191f77fa
          ports:
            - containerPort: 80
---

