apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-frontend
  template:
    metadata:
      labels:
        app: vue-frontend
    spec:
      containers:
        - name: vue
          image: wngud1/vue-frontend:main-f064b3744fbd7e0885ca37fce4ff14efc489268f
          ports:
            - containerPort: 80
