apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-frontend
  template:
    metadata:
      labels:
        app: vue-frontend
    spec:
      containers:
        - name: vue
          image: wngud1/vue-frontend:main-223183a3e099fa4f134c88af00b9aa6ebf3c7f1b
          ports:
            - containerPort: 80
