apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-frontend
  template:
    metadata:
      labels:
        app: vue-frontend
    spec:
      containers:
        - name: vue
          image: wngud1/vue-frontend:main-3c0e17114398f4599c0c570809eee69d8c7a11c1
          ports:
            - containerPort: 80
