apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-frontend
spec:
  selector:
    matchLabels:
      app: vue
  template:
    metadata:
      labels:
        app: vue
    spec:
      containers:
        - name: vue
          image: wngud1/vue-frontend:main-26fd338b84467ff81332f3fef50761565c551980
          ports:
            - containerPort: 80
---

