apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-frontend
  template:
    metadata:
      labels:
        app: vue-frontend
    spec:
      containers:
        - name: vue
          image: wngud1/vue-frontend:main-d297a47ce2a63099e5447f7a9fdd4c04118ddac4
          ports:
            - containerPort: 80
